In [20]:
import numpy as np
import pandas as pd

In [11]:
lst = [1,2,3]
#creating a numpy array
array = np.array(lst) 
print(array)

[1 2 3]


[1 2 3]

In [10]:
type(array)

numpy.ndarray

numpy.ndarray

In [22]:
#2d array
array2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
pd.DataFrame(array2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[21,22,23],[24,25,26]]])
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [21, 22, 23],
        [24, 25, 26]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
#dimension of numpy array
array.ndim
array2.ndim
array3.ndim

3

1 2 3


In [35]:
array10 = np.array([[[[[[[[[[1,2,3]]]]]]]]]])
array10

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [36]:
array10.ndim

10

10

In [37]:
#total number of items
array10.size 

3

3