In [1]:
import numpy

In [3]:
#creating an array filled with 1s
one_matrix = numpy.ones((2,3),dtype=int)
one_matrix

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
#creating an array filled with 0s
zero_matrix = numpy.zeros((2,3),dtype=int)
zero_matrix

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
#generates numbers between the given range
number_between_range = numpy.arange(3,15,2)
number_between_range

array([ 3,  5,  7,  9, 11, 13])

In [9]:
#genertae random number between range
random_number_between_range = numpy.random.randint(1,10,size=(4,5))
random_number_between_range

array([[1, 4, 8, 3, 4],
       [6, 1, 7, 3, 6],
       [9, 5, 9, 4, 8],
       [9, 6, 6, 5, 7]])