In [1]:
import numpy as np

In [2]:
array = np.array([[1,2],[3,4]])
array

array([[1, 2],
       [3, 4]])

In [3]:
#acessing an array
array[0] 

array([1, 2])

In [5]:
array[0][1:], array.shape

(array([2]), (2, 2))

In [6]:
#another way to acess index
array[0,1]

2

In [9]:
#acessing 3d array
array3d = np.array([[[1,3,4],[5,6,7]],[[8,9,8],[7,6,5]]])
array3d

array([[[1, 3, 4],
        [5, 6, 7]],

       [[8, 9, 8],
        [7, 6, 5]]])

In [12]:
array3d[1,1,2]

5