In [13]:
import numpy as np

In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.add(arr1,arr2)
#adds multiple arrays

array([5, 7, 9])

In [15]:
arr1 = np.array([1,4,2,3])
arr2 = np.array([4,5,6])
np.add(arr1,arr2)
#it shows us error the hsape of the array shoiuld be equal

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
np.sum(arr3,axis=0)
#gives sum of x axis

In [16]:
np.sum(arr3,axis=1)
#gives usm in y axis

array([ 6, 15, 24])

In [17]:
np.prod(arr3,axis=1)
#gives the product

array([  6, 120, 504])

In [18]:
np.min(arr3)

1

In [22]:
arr4 = np.array([[1,2,1],[4,5,5],[7,8,9]])
np.minimum(arr3,arr4)

array([[1, 2, 1],
       [4, 5, 5],
       [7, 8, 9]])

In [23]:
np.mean(arr4) #mean

4.666666666666667

In [24]:
np.std(arr4) #standard deviation

2.788866755113585

In [25]:
np.var(arr4) #variance

7.777777777777778