In [37]:
import numpy as np 
import pandas as pd 

In [38]:
n = 3

In [22]:
2**3

8

with 3 bits we can store upto 8 digits

In [23]:
np.int8

numpy.int8

In [24]:
arr = np.array([1,3,3,2])
arr

array([1, 3, 3, 2])

**For finding datatypes**

In [25]:
arr.dtype

dtype('int64')

**CREATE AN ARRAY WITH FLOAT DATAYPE EVENTHOUGH IT IS INTEGER**

In [26]:
arr1 = np.array([1,2,3,4],dtype=np.float32)
arr1

array([1., 2., 3., 4.], dtype=float32)

In [27]:
matrix = np.array([
    [1,2,3,4],
    [3,4,5,6],
    [3,2,1,1]
])
matrix

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [3, 2, 1, 1]])

In [28]:
matrix.shape

(3, 4)

In [29]:
matrix.ndim

2

In [30]:
matrix.size

12

**STATISTICS**

In [31]:
arr = np.array([1,2,3,4])

In [32]:
arr.sum()

10

In [33]:
arr.std()

1.118033988749895

In [34]:
arr.mean()

2.5

In [35]:
arr.var()

1.25

**BOOLEAN ARRAYS**

In [40]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [41]:
arr[0],arr[1]

(0, 1)

In [43]:
arr[[0,1]]

array([0, 1])

In [44]:
arr[[True,False ,True,False]]

array([0, 2])

In [47]:
arr>=2

array([False, False,  True,  True])

In [48]:
arr[arr>=2]

array([2, 3])

In [51]:
arr[arr>arr.mean()]

array([2, 3])

In [52]:
arr[~(arr>arr.mean())]

array([0, 1])

In [54]:
arr[(arr==0)|(arr==1)]

array([0, 1])

In [56]:
arr[arr%2==0]

array([0, 2])

In [57]:
arr[arr%2]

array([0, 1, 0, 1])

**LINEAR ALGEBRA**

In [59]:
M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
N = np.array([
    [11,12,13],
    [14,15,16],
    [17,18,19]
])
M,N

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [60]:
M.dot(N)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [61]:
M@N

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [62]:
M.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [63]:
N.T @ M

array([[186, 228, 270],
       [198, 243, 288],
       [210, 258, 306]])

**SIZE OF OBJECTS MEMORY**

In [67]:
import sys
sys.getsizeof(1)

28

In [70]:
np.dtype(int).itemsize

8

In [71]:
np.dtype(np.int8).itemsize

1

In [72]:
np.dtype(float).itemsize

8

In [81]:
l = list(range(1000000))
arr = np.arange(1000000)

In [85]:
%time np.sum(arr*2)

CPU times: user 4.8 ms, sys: 801 µs, total: 5.6 ms
Wall time: 3.44 ms


999999000000

In [86]:
%time sum([i**2 for i in l])

CPU times: user 354 ms, sys: 18.8 ms, total: 373 ms
Wall time: 374 ms


333332833333500000

**NUMPY FUNCTIONS**